### ISSUE TITLE
exec: "gcc": executable file not found in $PATH

### ISSUE THREAD

**Issue by CairoLee** [caddyserver/caddy-docker#101]
### Hello Caddy

I trying to build caddy with custom modules in docker. but i get a error like:

> exec: "gcc": executable file not found in $PATH

### Environment
- macOS 10.15.5
- Docker version 19.03.8, build afacb8b
- Docker Desktop Version 2.3.0.3
- Here is my gcc information in the Docker Host Machine:

```
% gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.3 (clang-1103.0.32.29)
Target: x86_64-apple-darwin19.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

### Dockerfile

Here is my Dockerfile follow [https://hub.docker.com/_/caddy](https://hub.docker.com/_/caddy):

```
FROM caddy:2.1.1-builder AS builder

RUN caddy-builder \
    github.com/caddyserver/nginx-adapter \
    github.com/abiosoft/caddy-json-parse

FROM caddy:2.1.1

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

When i build this dockerfile, it throw the error like:

```
% docker build -t cairolee:test .
Sending build context to Docker daemon  3.072kB
Step 1/4 : FROM caddy:2.1.1-builder AS builder
 ---> fae42fca94e0
Step 2/4 : RUN caddy-builder     github.com/caddyserver/nginx-adapter     github.com/abiosoft/caddy-json-parse
 ---> Running in 718da7e6f21a
+ go get github.com/caddyserver/nginx-adapter github.com/abiosoft/caddy-json-parse
go: downloading github.com/abiosoft/caddy-json-parse v0.0.0-20200527143927-f6a50fd2b066
go: downloading github.com/caddyserver/nginx-adapter v0.0.2
go: github.com/abiosoft/caddy-json-parse upgrade => v0.0.0-20200527143927-f6a50fd2b066
go: github.com/caddyserver/nginx-adapter upgrade => v0.0.2
go: downloading github.com/caddyserver/ntlm-transport v0.1.1-0.20200409193839-5d99ab17e974
# github.com/DataDog/zstd
exec: "gcc": executable file not found in $PATH
The command '/bin/sh -c caddy-builder     github.com/caddyserver/nginx-adapter     github.com/abiosoft/caddy-json-parse' returned a non-zero code: 2
```

### Question

How to fix this? is it my operate mistake? Please help~~

**Comment by hairyhenderson** [comment]
Hi @CairoLee - the error is happening because you don't have `gcc` inside your build image. Apparently one of the modules requires `gcc` to build.

I haven't tested this so not sure if it'll work as-is, but you could try something like this:

```docker
FROM caddy:2.1.1-builder AS builder

RUN apk add --no-cache gcc
RUN caddy-builder \
    github.com/caddyserver/nginx-adapter \
    github.com/abiosoft/caddy-json-parse

FROM caddy:2.1.1

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

It's a bit strange that it would even attempt to use `gcc` since `CGO_ENABLED=0` is set 🤔...

**Comment by hairyhenderson** [comment]
Also taking a brief look at those modules, it isn't immediately clear why `github.com/caddyserver/ntlm-transport` is pulling in `github.com/DataDog/zstd` 🤔

/cc @Mohammed90 @mholt @abiosoft - do any of you have any idea?

**Comment by Mohammed90** [comment]
Looking at it, I get this:
```bash
 $ go mod why github.com/DataDog/zstd
# github.com/DataDog/zstd
caddy
github.com/caddyserver/caddy/v2/modules/standard
github.com/caddyserver/caddy/v2/modules/caddypki/acmeserver
github.com/smallstep/nosql
github.com/smallstep/nosql/badger/v2
github.com/dgraph-io/badger/v2
github.com/dgraph-io/badger/v2/y
github.com/DataDog/zstd
```

Badger [has a file for `!cgo`](https://github.com/dgraph-io/badger/blob/master/y/zstd_nocgo.go), so not sure why it's still requires gcc.

**Comment by Mohammed90** [comment]
PR #102 fixes it in my local tests.

**Comment by hairyhenderson** [comment]
The `caddy:2.1.1-builder` image will be updated after https://github.com/docker-library/official-images/pull/8339 merges. Thanks for reporting this, @CairoLee, and sorry for the inconvenience!

**Comment by hairyhenderson** [comment]
FYI the official builder is updated and it looks fixed to me!

**Comment by CairoLee** [comment]
Thanks for @hairyhenderson and @Mohammed90 participating in the discussion, it's solved now ; )
