### ISSUE TITLE
DNS Provider Plugin Modules?

### ISSUE THREAD

**Issue by CrafterLaughter** [caddyserver/caddy-docker#105]
Feature Request.

Is it on the roadmap to add the DNS provider plugin modules to the official caddy docker images?  If I'm not mistaken each DNS provider plugin is only maybe 100KB so hopefully people wouldn't think they add too much bloat?

It would be great to be able to use the latest official images, but if not possible for this use case, is anyone aware of a caddy docker image that does have DNS provider plugin modules other than the abiosoft/caddy on docker hub?  That image has the cloudflare module (fortunately the one I need) but it's Caddy 1.0.3.

**Comment by francislavoie** [comment]
You can easily build your own Docker image with the modules you need using the builder variant of the Caddy image.

Please see the documentation on Docker Hub https://hub.docker.com/_/caddy/ specifically the section "Adding custom Caddy modules".
