### ISSUE TITLE
Consider how to build custom images without a Dockerfile, using build args for plugins

### ISSUE THREAD

**Issue by hairyhenderson** [caddyserver/caddy-docker#108]
In https://github.com/lucaslorentz/caddy-docker-proxy/pull/176, @lucaslorentz has suggested an optimization to provide an alternate way to build a custom image, where the only changes are plugin installations.

Effectively, this approach uses a build arg to provide a list of plugins to be installed, and uses a [remote Git context](https://docs.docker.com/engine/reference/commandline/build/#git-repositories) to reference the `Dockerfile` from GitHub.

It could look something like:

```console
$ docker build --build-arg "CADDY_PLUGINS=github.com/caddyserver/nginx-adapter github.com/hairyhenderson/caddyprom" -t mycustomcaddy:latest https://github.com/caddy/caddy-docker.git#:custom-build
```

Personally I'm ambivalent, since I generally prefer that people write their own `Dockerfile`s so that the build is more predictable and reproducible (better to put a `Dockerfile` in git than a shell script with a complex `docker build` command). But in some ways this may make it slightly easier for some users to consume Caddy in Docker.

One big hitch with this approach is that this repo is currently focused on _only_ the official `caddy` images, and official images are not permitted to contain `ARG` instructions (due to reproducibility requirements). So _if_ a `Dockerfile` were added to support this use-case, it would need to be made abundantly clear that there are no published images based on it.

**Comment by francislavoie** [comment]
Yeah I'm definitely pro-Dockerfile here. I don't think build args are the right choice for an official image. We haven't had any complaints about the current workflow (builder image) outside of this discussion yet.

**Comment by xnaas** [comment]
Personally, I would love for there to be a way to pass an ARG or ENV into the official image to add plugins.

Right now I have to manage my own Dockerfile for Caddy and only Caddy. Everything else I use can pass simple environment variables in to resolve plugins/extensions/etc.

**Comment by polarathene** [comment]
I wanted to test out the 2.2 RC which official images understandably don't publish. It wasn't entirely clear what needed changing (some hard-coded versions in strings and my platform checksum).

Having an unofficial dev image with a build arg for that would be useful to copy the Dockerfile locally and pass any needed ARGs to `docker build` (else just modify the ARG defaults in the Dockerfile, ARG would be more clear what I need to change).

**Comment by francislavoie** [comment]
The preferred approach for building from an arbitrary commit of Caddy would be to use `xcaddy`. This is WIP in this PR: https://github.com/caddyserver/caddy-docker/pull/109. I don't think adding ARGs to the main docker image has much value when `xcaddy` can solve that as well.

**Comment by hairyhenderson** [comment]
Let's close this for now and see what kind of need arises that using a `Dockerfile` can't address.
