### ISSUE TITLE
Usage overview?

### ISSUE THREAD

**Issue by sosodev** [caddyserver/caddy-docker#11]
I'm testing this image at the moment and while I think I've got it working correctly it would be nice to have a little bit of guidance on the best way to set it up. Maybe add a couple of examples to the readme? :)

**Comment by mholt** [comment]
Oh, yes I've been wanting to finish the welcome page for this, too. @Ilyes512 or @hairyhenderson could we work on this together this week?

**Comment by Ilyes512** [comment]
So I would say there are two main environments:

- development environment
  - uses host volumes (so you can change the files on your host and see the changes without needing to rebuild the image)
  - I use docker-compose for local development.
- non-developing environment
  - you build your own image with caddy docker as the base image (usually you do this with CI/CD)
  - image is immutable (files are copied into the image, except for of course secrets, if you have any)
  - you ideally would run it on a Kubernetes cluster

I will write some down. I think a dedicated examples dir is a good place (I know caddy has a dedicated examples repo, but I think it’s best to keep these examples in the docker repo).

**Comment by sosodev** [comment]
Are the images in an official repository anywhere yet?

**Comment by Ilyes512** [comment]
Not yet. They will hopefully be soon available under the caddy org and later also as docker official images.

**Comment by coral** [comment]
Yeah I'm confused for example on how to access the JSON admin endpoint in the docker image since it's only listening to 127.0.0.1

**Comment by francislavoie** [comment]
@coral for that you need to change the admin endpoint either by loading an initial Caddyfile or JSON config. See the "admin" option here https://caddyserver.com/docs/caddyfile/options you can set "0.0.0.0". Make sure that this port is not publicly accessible though, because attackers could do bad things.

For reference, the best place to ask usage questions is on https://caddy.community

**Comment by coral** [comment]
@francislavoie Yeah figured that out. Do you want me to add this as documentation for this repo? I'll happily help you write some sort of getting started with the container

**Comment by pulverize** [comment]
Having not worked with docker-compose nor CI/CD outside of a full MS stack I'm floundering a bit with the laconic readme and this would be very much appreciated..

**Comment by francislavoie** [comment]
@pulverize the best place to ask for help is on https://caddy.community. Be sure to read up on docker/docker-compose first, understanding the fundamentals of Docker is pretty important if you plan on using using it that way.
