### ISSUE TITLE
Publish RCs/Betas as images to docker hub

### ISSUE THREAD

**Issue by techknowlogick** [caddyserver/caddy-docker#133]
Now that https://github.com/caddyserver/caddy/releases/tag/v2.3.0-beta.1 has been published, would it be possible to publish these as images to the hub as well?

**Comment by francislavoie** [comment]
What you can do actually, is use the builder image variant which uses xcaddy, to make your own build of Caddy with whatever tag or commit you want.

The only thing that's actually different between versions of the container is the Caddy binary (unless we make other changes to the container for meta reasons), so it's fine to do that.

You don't need to specify any plugins with xcaddy, it can just be a vanilla build.

For example, you'd use this xcaddy command to get the current beta:

```
xcaddy build v2.3.0-beta.1
```

Or to build from master:

```
xcaddy build master
```

Publishing new Docker tags unfortunately isn't automated, we need to update the checksums in this repo, generate the new Dockerfiles, then make a pull request against the docker-library repo for it to be reviewed by the Docker official image maintainers, then it goes through their Jenkins pipeline. So we try to avoid doing it for beta releases.

**Comment by techknowlogick** [comment]
> Publishing new Docker tags unfortunately isn't automated, we need to update the checksums in this repo, generate the new Dockerfiles, then make a pull request against the docker-library repo for it to be reviewed by the Docker official image maintainers, then it goes through their Jenkins pipeline. So we try to avoid doing it for beta releases.

Ah that makes sense. Thanks for the detailed response and possible solution. I will close this now as what you’ve suggested works for me :)

**Comment by hairyhenderson** [comment]
Sorry, I'd meant to get to releasing the beta 😓. Will try to get to it this weekend!
