### ISSUE TITLE
docker version is 2.2 

### ISSUE THREAD

**Issue by bigfoxtail** [caddyserver/caddy-docker#137]
.github/workflows/docker.yml is not update, docker version is 2.2

**Comment by hairyhenderson** [comment]
Hi @bigfoxtail, thanks for logging this issue! We recommend that people use the official image (the `caddy` one at https://hub.docker.com/_/caddy), though that one has not yet been updated (there is a pending PR here:  https://github.com/docker-library/official-images/pull/9365).

However, the `caddy/caddy` image should also be up-to-date, so thanks for pointing it out!

**Comment by hairyhenderson** [comment]
Fixed in https://github.com/caddyserver/caddy-docker/commit/f149d1f54318f62bd01ab68e00276a24a017f097
