### ISSUE TITLE
Release 2.3.0 Docker image

### ISSUE THREAD

**Issue by Serneum** [caddyserver/caddy-docker#138]
It looks like [Dockerhub](https://registry.hub.docker.com/_/caddy) is only showing 2.1.1, 2.2.1, and 2.3.0-rc1. Can it be updated with the 2.3.0 images?

**Comment by hairyhenderson** [comment]
@Serneum The PR's pending: https://github.com/docker-library/official-images/pull/9365

Please note that it can take a few days after a release of Caddy for the official docker image to be updated. And, things should be expected to take longer around the holidays 😉

**Comment by Serneum** [comment]
Awesome, I didn't know that official images worked through a PR process instead of just a push. Thanks!
