### ISSUE TITLE
Caddy and Nextcloud in Docker, how to add headers in docker-compose file

### ISSUE THREAD

**Issue by zilexa** [caddyserver/caddy-docker#141]
Wondering how to use caddy-docker with Nextcloud in docker (and OnlyOffice document server, Firefox Sync, FileRun also in docker and Syncthing running bare metal). 

I am following the example posted [here](https://www.reddit.com/r/NextCloud/comments/gn7fdl/looking_for_caddy_v2_sample_config_for_nextcloud/): 

```
nextcloud.example.com {

        root    * /var/www/nextcloud
        file_server
        log {
                output file     /var/log/caddy/nextcloud.log
                format single_field common_log
        }

        php_fastcgi 127.0.0.1:9000

        header {
                # enable HSTS
                Strict-Transport-Security max-age=31536000;
        }

        redir /.well-known/carddav /remote.php/dav 301
        redir /.well-known/caldav /remote.php/dav 301

        # .htaccess / data / config / ... shouldn't be accessible from outside
        @forbidden {
                path    /.htaccess
                path    /data/*
                path    /config/*
                path    /db_structure
                path    /.xml
                path    /README
                path    /3rdparty/*
                path    /lib/*
                path    /templates/*
                path    /occ
                path    /console.php
        }

        respond @forbidden 404

}
```

But with caddy-docker, do I still need to define each docker container that I want to expose to a `customname.mydomain.com` in the Caddyfile? Or can I purely rely on labels in docker-compose?

If I have nextcloud working on files.mydomain.com, I'm happy and I'm sure I can figure out the other services with Nextcloud as example.

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
