### ISSUE TITLE
using custom certificates

### ISSUE THREAD

**Issue by andrewoconnor** [caddyserver/caddy-docker#176]
I am trying to use custom certificates with caddy docker. I have placed them in data/caddy/certificates/ like this:

```
example.com:443 {
    tls /data/caddy/certificates/example.com/example.com.crt /data/caddy/certificates/example.com/example.com.key
    root * /srv
    file_server
}
```
This works fine, however as soon as I start the container the certificates disappear from this directory. If I need to restart my container the certificates need to be copied in again. How can I avoid this when using my own custom certificates?

**Comment by francislavoie** [comment]
You shouldn't use `data` for your own files. That directory is meant to be entirely managed by Caddy. Instead, mount those elsewhere, like `/certs` or something, with a separate volume.
