### ISSUE TITLE
add health-checking to the dockerfile

### ISSUE THREAD

**Issue by MCWertGaming** [caddyserver/caddy-docker#185]
It would be nice if the docker-deamon could do regular and frequent health checks to make sure that caddy is healthy and running normally. I'm not sure, if caddy has something like an health page (like domain/health) build in or if it's possible with a different approach.

**Comment by francislavoie** [comment]
> I'm not sure, if caddy has something like an health page (like domain/health) build in

It doesn't, because the meaning of "health" differs based on the usecase, and Caddy is "too flexible" for that to be definite.

Best if you implement that yourself according to your own needs.

**Comment by MCWertGaming** [comment]
Okay, thank you really much!
