### ISSUE TITLE
Alpine 3.13 breaks ARM images

### ISSUE THREAD

**Issue by Forinil** [caddyserver/caddy-docker#199]
Using Alpine 3.13 as a base breaks Cadddy's ARM images, due to this: [No network connection on alpine:edge on raspberry pi](https://gitlab.alpinelinux.org/alpine/aports/-/issues/12091).

Downgrading Alpine to 3.12 solves the issue.

Tested on _Raspberry Pi 4 Model B Rev 1.2_ with _Raspbian 10 (buster) aarch64_ with kernel 5.10.17-v8+.

**Comment by hairyhenderson** [comment]
@Forinil did the workaround listed in that doc solve the issue?

What version of Docker are you using?

**Comment by Forinil** [comment]
I'm using Docker 20.10.7.

I've confirmed that both setting `seccomp=unconfined` and rebuilding the image with Alpine 3.12 as base are valid workarounds. I haven't tried anything else.

**Comment by hairyhenderson** [comment]
Ok. As the issue [confirms](https://gitlab.alpinelinux.org/alpine/aports/-/issues/12091#note_145160), this is an upstream issue that's being worked on.

There's no action that we need to take in this repo, so I'm going to close this issue.
