### ISSUE TITLE
Create and use caddy user instead of root

### ISSUE THREAD

**Issue by Ilyes512** [caddyserver/caddy-docker#2]
Run caddy with the `caddy` user instead of root. Also check if we can run it with all privileges dropped (See https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities).

Note: Using a port as a non-root user lower than 1024 requires the `CAP_NET_BIND_SERVICE` privilege. You can circumvent this by using a port higher than 1024. 

Giving the binary `CAP_NET_BIND_SERVICE` on alpine:

```
RUN apk add --no-cache --no-progress libcap \
    && setcap 'CAP_NET_BIND_SERVICE=+pie' /usr/bin/caddy
```

Reading materials:

- http://man7.org/linux/man-pages/man7/capabilities.7.html
- https://towardsdatascience.com/top-20-docker-security-tips-81c41dd06f57
- https://pythonspeed.com/articles/root-capabilities-docker-security/

**Comment by hairyhenderson** [comment]
This was done, but then we decided not to do this anymore seeing all the issues it caused, plus simplicity! (see #30)
