### ISSUE TITLE
Support adding custom plugins

### ISSUE THREAD

**Issue by zakcutner** [caddyserver/caddy-docker#25]
I'm new to Caddy so apologies if this question is obvious... I'm trying to add a plugin to my Caddy setup running on Docker. As I understand it, this is done by simply [adding a new import to `run.go`](https://github.com/caddyserver/caddy/blob/master/caddy/caddymain/run.go#L42).

However, to make this change I require my own (almost identical) `Dockerfile` which compiles a modified version of `run.go`. Is there a better way to go about this or is it possible to somehow edit `run.go` whilst using this `Dockerfile`?

It seems that other `Dockerfile`s for Caddy [allow the addition of some plugins using build arguments](https://github.com/abiosoft/caddy-docker#custom-plugins), is there something like this that will be implemented in this repository? Thanks 😄

**Comment by mholt** [comment]
You can make your own `main` with your own imports, without changing any of Caddy's source code. Would that help?

**Comment by zakcutner** [comment]
@mholt Thanks for the suggestion! It is really cool you can do that although unfortunately that method is currently incompatible with the Dockerfile — see #27 for a discussion on updating this.
