### ISSUE TITLE
Tag minor version

### ISSUE THREAD

**Issue by vincentchalamon** [caddyserver/caddy-docker#265]
Hi,

Thanks for Caddy, it's an awesome project I'm working with since years and implementing it in many projects!

In API Platform as on many projects, we're using `caddy:2-alpine` Docker image to get the latest bugfixes on Caddy 2.*. But I couldn't find any `2.5-alpine` tag on it, is there any reason to not tag a minor version but only major and bugfix versions on the Caddy official Docker image?

Recently, Caddy 2.6 has been released which changes the configuration. For instance, we were using `servers.protocol.experimental_http3` which has been removed: the caddy service couldn't start anymore.

**Comment by vincentchalamon** [comment]
Hi @hairyhenderson,
I don't know if you're the right person to ask, if not, sorry for the inconvenience!
Do you know any reason not tagging a minor version on the Docker image? For instance: `2.6-alpine`
Thanks in advance for your answer

**Comment by hairyhenderson** [comment]
@vincentchalamon There's no strict reason _not_ to tag the minor.

I'll consider this! @francislavoie can you think of any reason why we shouldn't add minor tags?

**Comment by francislavoie** [comment]
No objections from me.

**Comment by hairyhenderson** [comment]
I've issued #267 to add the `2.6[-*]` set of tags

**Comment by hairyhenderson** [comment]
The change is merged, and this'll be available in the official repo when this PR merges: https://github.com/docker-library/official-images/pull/13422

Note that this only adds a minor tag starting with `2.6` - we will not be making a `2.5` set of tags.
