### ISSUE TITLE
Increase UDP buffer size

### ISSUE THREAD

**Issue by natachasouza** [caddyserver/caddy-docker#269]
When running caddy in a docker container, we get this message in the logs:

`{"level":"info","ts":1668215276.045424,"msg":"failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details."}`

Searching in the Caddy community, there are only instructions on how to increase the buffer size on the operating system: https://caddy.community/t/udp-receive-buffer-size-quic/11244

Can the base docker image for caddy have this buffer size increased? 

Please let me know if you need additional info!

**Comment by francislavoie** [comment]
I'm pretty sure you need to do that on the host machine, not in the container.

**Comment by vbertr01-hub** [comment]
I have also the same message but we are using a fargate ecs container so we can not increase this buffer size.  Will this give problems or is there a workaround?

**Comment by mholt** [comment]
It just means your HTTP/3 performance is suboptimal. It would be ideal if your environment increased the buffer size (or allowed you to do so).

**Comment by natachasouza** [comment]
Thank you @francislavoie and @mholt for the explanations.
