### ISSUE TITLE
Build failing for 2.6.4

### ISSUE THREAD

**Issue by jarredwitt** [caddyserver/caddy-docker#283]
Hello,

I have the following Dockerfile:

```
FROM caddy:2.6.4

COPY Caddyfile /etc/caddy/Caddyfile
```

When I go to deploy I get the following error:
```
standard_init_linux.go:228: exec user process caused: operation not permitted
```

This error also occurs for 2.6.3, but doesn't occur for 2.6.2.

**Comment by francislavoie** [comment]
Are you sure you pulled down the correct image for your CPU architecture?

**Comment by jarredwitt** [comment]
So I pulled the following images and got the same `operation not permitted` error (deploying via render.com):

```
2.6.3, 2.6.3-alpine, 2.6.4, 2.6.4-alpine
```

I finally tried 2.6.4-builder-alpine and that ended up deploying successfully.

**Comment by hairyhenderson** [comment]
@jarredwitt this looks to me like an issue with your environment - you'll need to provide more details about your environment (how are you building? what versions of all software involved in building? how are you deploying? what versions of all software involved in deploying?)

**Comment by hairyhenderson** [comment]
Closing due to lack of response
