### ISSUE TITLE
Docker hub lists vulnerabilities

### ISSUE THREAD

**Issue by JVimes** [caddyserver/caddy-docker#284]
Are [these vulnerabilities](https://hub.docker.com/layers/library/caddy/latest/images/sha256-36ba71b44afa613ecf0aadce8e4b9e3f56e0c4b0a78c8edf4e8c2485f21b35ef) listed in the docker hub concerning?

![image](https://user-images.githubusercontent.com/6148201/223507352-31ac4928-4ec4-43d4-bc82-dbfd8014406a.png)

**Comment by francislavoie** [comment]
Almost all of those are from very old Go versions. It's not relevant.

**Comment by JVimes** [comment]
Thank you, does that mean caddy:latest is using an old Go version for ARMv7?

**Comment by mholt** [comment]
No, we always use the latest Go version.

**Comment by JVimes** [comment]
Great. Just to clarify, this makes Caddy look worse to potential new users:

![image](https://user-images.githubusercontent.com/6148201/223522786-255868a5-ff39-4de6-8c53-d9012e9dcd9c.png)

**Comment by mholt** [comment]
It should make it look _better_, as these are discovered and patched vulnerabilities. Who knows how many more memory vulns lurk in the dark of NGINX and HAProxy.

**Comment by hairyhenderson** [comment]
I think this is actually a bug in the DockerHub vuln scanning - my gut feeling is that Go 1.20 is being misinterpreted as Go 1.2 (I've seen that a bunch in other systems that parse the number as a float instead of a version string).

For example, it's reporting a very old issue fixed in Go 1.4.3, which we're definitely not vulnerable to 😂

**Comment by JVimes** [comment]
Thanks for the quick response, all. I hope Docker Hub fixes it.

**Comment by hairyhenderson** [comment]
they fixed it pretty fast: 
<img width="1229" alt="image" src="https://user-images.githubusercontent.com/2037086/223573736-3a2eab32-7983-45ac-800e-b5d4e34a2aff.png">

**Comment by mholt** [comment]
Ha, thanks for reporting that!
