### ISSUE TITLE
Use caddy non root user in caddy container

### ISSUE THREAD

**Issue by K2ouMais** [caddyserver/caddy-docker#293]
Hello everyone,

this is not an issue, but a question.

Is there a way to use a non root user in the container? Or do I have to build an image myself?

Because it beeing root, I cant use it in our Kubernetes cluster, because of the policies.

Nginx has unprivileged containers on Dockerhub, but I would love to use caddy because of simplicity.

Thanks in advance

**Comment by hairyhenderson** [comment]
See https://github.com/caddyserver/caddy-docker/issues/104 and #274

**Comment by gyzerok** [comment]
Hello @hairyhenderson! Maybe I am missing something but I don't see any instructions on how to run as non-root in the image docs nor in the issue/PR you've mentioned. Would appreciate your help here.

**Comment by hairyhenderson** [comment]
@gyzerok this was closed because it was a duplicate - see the discussion in #104
