### ISSUE TITLE
Docker images with DNS modules

### ISSUE THREAD

**Issue by vincentchov** [caddyserver/caddy-docker#295]
Hi, I'm looking for a Caddy image with Cloudflare support without having to build it. If you can't make one, how would I go about making it official/trusted? Would I be able to have a repo made under the "caddyserver" organization?

I'd intend to use the Renovate bot to use the builder image and add the Cloudflare module whenever the builder image is updated.

Thanks!

**Comment by hairyhenderson** [comment]
@vincentchov you can build one yourself in your own repo... Is there a reason it needs to be official?

**Comment by vincentchov** [comment]
I figured if the only change was to add the Cloudflare module, it might as well be official. But if that's hard to do, I suppose I could make my own repo for it

**Comment by francislavoie** [comment]
Caddy modules are separate on purpose. If we offered official builds with specific plugins, where do we draw the line on the combinations to support? It just doesn't make sense for us to do.

We provide the builder image variant specifically to make it as easy as possible for users to make builds of Caddy with just the plugins they need with a simple ~4-line Dockerfile.
