### ISSUE TITLE
Build failed with 2.6.4-builder-alpine, 2.6-builder-alpine, 2-builder-alpine, builder-alpine

### ISSUE THREAD

**Issue by adrien2go** [caddyserver/caddy-docker#301]
Hello,

(2)(.6)(.4)(-)builder-alpine tags linked from https://github.com/caddyserver/caddy-docker/blob/8a3bab4e266cc4e32c57d757890bbc1b6ff54e1d/2.6/builder/Dockerfile
and not at https://github.com/caddyserver/caddy-docker/blob/master/2.6/builder/Dockerfile
so golang:1.19-alpine is used and not golang:1.20-alpine

Is it possible to change it?

**Comment by hairyhenderson** [comment]
This will be fixed in the 2.7 image (#305)
