### ISSUE TITLE
2.7-alpine warning: "certutil" is not available

### ISSUE THREAD

**Issue by ikluft** [caddyserver/caddy-docker#303]
The 2.7-alpine container image displays a warning, and fails to start unless it's fixed:

`INFO    warning: "certutil" is not available, install "certutil" with "apt install libnss3-tools" or "yum install nss-tools" and try again`

The fix is to install the [nss-tools](https://pkgs.alpinelinux.org/package/v3.18/community/x86_64/nss-tools) apk package.

[run-caddy-issue.txt](https://github.com/caddyserver/caddy-docker/files/11878572/run-caddy-issue.txt)

**Comment by francislavoie** [comment]
That's just a warning, and it does not fail to start. You can safely ignore that.

When using the internal issuer, Caddy attempts to install its root cert using multiple approaches. Using certutil is one of those approaches.

It's only needed if you have any software in the container which uses nss. Caddy does not, so it doesn't need it.
