### ISSUE TITLE
2.7.2 should not be used, update to 2.7.3

### ISSUE THREAD

**Issue by TastyPi** [caddyserver/caddy-docker#307]
See https://github.com/caddyserver/caddy/releases/tag/v2.7.3

**Comment by AskAlice** [comment]
How is this not automated? o.o

**Comment by Jiehong** [comment]
I was also wondering the same: 5 days ago the caddy release said not to use 2.7.2, and use 2.7.3 but docker pull shows it doesn't exist (and indeed it isn't on https://hub.docker.com/_/caddy).

The release notes does not mention the docker images being slightly out of sync, so for me the workaround was to just keep on using 2.6.4 for now.
Perhaps just always adding a note in https://github.com/caddyserver/caddy/releases telling people to expect some delays in the docker image release would be nice.


Also, has it been considered to publish on github packages? (https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages)

**Comment by francislavoie** [comment]
This is now pending https://github.com/docker-library/official-images/pull/15189 being merged.

Thanks for being patient, everyone.
