### ISSUE TITLE
how to reverse proxy to other docker containers?

### ISSUE THREAD

**Issue by neuronflow** [caddyserver/caddy-docker#32]
Could you please provide an example how to use the docker and especially how I can reverse proxy requests to other docker containers?

https://caddy.community/t/how-to-run-caddy-v2-inside-a-docker-container-and-reverse-proxy-between-docker-containers/7025

**Comment by hairyhenderson** [comment]
Hi @neuronflow - I've added docs now with some basic examples on this repo (https://github.com/caddyserver/caddy-docker), and it looks like you got some help on the forum. So I'm going to close this now. Feel free to respond on the forum post if you have any follow-up questions!
