### ISSUE TITLE
Builder tag not friendly for variables

### ISSUE THREAD

**Issue by dkarlovi** [caddyserver/caddy-docker#328]
Currently, the `-builder` part of the tag is **embedded** into the builder image tag, like so
```
caddy:2.7.4-alpine
caddy:2.7.4-builder-alpine
````

A nice improvement would be to **append** the builder as a suffix on the tag, like so

```
caddy:2.7.4-alpine
caddy:2.7.4-alpine-builder
````

This would allow using a single value for the Caddy Docker image and its builder just by appending `-builder`, not have two separate values.

```
${CADDY_DOCKER_IMAGE}
${CADDY_DOCKER_IMAGE}-builder
```

**Comment by francislavoie** [comment]
Just remove the `-alpine` part from your env var. `2.7.5` and `2.7.5-builder` will yield the same alpine images. See the Shared Tags https://hub.docker.com/_/caddy

**Comment by dkarlovi** [comment]
> Just remove the -alpine part from your env var.

Not messing with the values is exactly why this issue was opened.

**Comment by francislavoie** [comment]
The problem is not worth our tags, the problem is with your variable. Update your variable, and it will work as you expect.

**Comment by dkarlovi** [comment]
Sure, that's what I'm already doing, the suggestion was to unbreak it upstream because the current tags are a bit of a mess, as discussed in OP.

Ideally, these images should be separate images (which share tags) because they represent a different final product, tweaking the tag as described would make it a little less messy.
