### ISSUE TITLE
Pass arguments to Caddy without config file

### ISSUE THREAD

**Issue by huntson** [caddyserver/caddy-docker#329]
On Windows I am running Caddy without a file and just passing arguments via a .bat file.  For a simple proxy setup, is there a way of passing something similar to the below without a config?

`Start "" "C:\Users\Production\Desktop\caddy\caddy_windows_amd64.exe" reverse-proxy --from :2300 --to 172.29.1.0:80
`

**Comment by francislavoie** [comment]
Yes, just set the command for the container.

But still, strongly recommended that you use a Caddyfile. Much more flexible.

**Comment by huntson** [comment]
Being unfamiliar with how to do that, can you please help?

**Comment by francislavoie** [comment]
It's covered in the docs here: https://hub.docker.com/_/caddy
