### ISSUE TITLE
Update to golang v1.22 for builder base

### ISSUE THREAD

**Issue by sam-lord** [caddyserver/caddy-docker#334]
I'm attempting to build a docker container with the experimental Tailscale plugin: https://github.com/tailscale/caddy-tailscale

My issue is that trying to build with a Dockerfile like this errors because the version of Golang is v1.21, and v1.22 is required for caddy-tailscale:

```Dockerfile
FROM caddy:2.7.6-builder AS builder

RUN xcaddy build \
    --with github.com/tailscale/caddy-tailscale

FROM caddy:2

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

**Comment by acouvreur** [comment]
Also intersted in that!

**Comment by brotbert** [comment]
@mholt Any plans to bump golang in the builder image? Our build also broke after your recent commits in [caddy-ratelimit](https://github.com/mholt/caddy-ratelimit) and bumping the required golang to v1.22 ([see here](https://github.com/mholt/caddy-ratelimit/blob/master/go.mod#L3)). Thanks!

**Comment by mholt** [comment]
@brotbert Dependabot broke the build; my follow-up commit fixed the build, but only broke those using old caddy versions apparently. The latest commit actually makes it work for old Caddy versions too: [2d18cd2c76cc5578483450f44f417bca8764a8bc](https://github.com/mholt/caddy-ratelimit/commit/2d18cd2c76cc5578483450f44f417bca8764a8bc)

**Comment by brotbert** [comment]
@mholt We appreciate the quick feedback on it, but unfortunately it still doesn't work because of the minimum required golang version: https://github.com/mholt/caddy-ratelimit/blob/master/go.mod#L3

See also for reference: https://go.dev/doc/modules/gomod-ref#go

**Comment by francislavoie** [comment]
> Any plans to bump golang in the builder image?

No, but you can use the 2.8.0-beta.2 builder image which has Go 1.22.

But I agree the `caddy-ratelimit` `go.mod` should be fully reverted to allow building with Go 1.21.

**Comment by francislavoie** [comment]
We're using Go 1.22 for Caddy v2.8.0 which is releasing now
