### ISSUE TITLE
caddy:2.7.6: getting missing instance.uuid file warning

### ISSUE THREAD

**Issue by geekodour** [caddyserver/caddy-docker#335]
version: `caddy:2.7.6`

This is a warning that I am getting, caddy is  running just fine. I was wondering if I am missing any config which would make sure caddy creates this file. I was running caddy directly on my system(non dockerized version), I can see that the instance.uuid file is being created there in the data directory but when I am using the docker version I am getting this warning on caddy initilization.

```
{"level":"info","ts":1714074416.7595403,"msg":"serving initial configuration"}
{"level":"warn","ts":1714074416.76022,"logger":"tls","msg":"unable to get instance ID; storage clean stamps will be incomplete","error":"open /data/caddy/instance.uuid: no such file or directory"}
```

What should I be doing to fix this?

**Comment by mholt** [comment]
Likely fixed already, based on a commit just a few months ago. https://github.com/caddyserver/caddy/issues/5976

**Comment by francislavoie** [comment]
Closing as inactive, I don't think there's anything actionable here.
