### ISSUE TITLE
Dockerhub 2.8.0 image is missing linux build

### ISSUE THREAD

**Issue by zephyros-dev** [caddyserver/caddy-docker#352]
As the title suggest, currently the [Dockerhub 2.8.0 image](https://hub.docker.com/layers/library/caddy/2.8.0/images/sha256-6a18978ffbc393583ec9e82d2f28c38093fb2c46658d422820d3aacff72a5adf?context=explore) is missing the linux build.

**Comment by francislavoie** [comment]
Yep, it's still in the build pipeline https://doi-janky.infosiftr.net/. It's out of our control. Have patience.
