### ISSUE TITLE
Missing Caddy v2.8.2 and v2.8.4

### ISSUE THREAD

**Issue by serfriz** [caddyserver/caddy-docker#354]
I believe the Dockers with Caddy v2.8.2 and v2.8.4 aren't in the build pipeline yet. Would it be possible to automate it for new releases? Thank you!

**Comment by mholt** [comment]
This has been asked a lot of times. Docker official images require manual processing and it's out of our control, sorry.

**Comment by francislavoie** [comment]
More specifically, I'm on vacation right now and it's a weekend - I'll start the process as soon as physically possible.
