### ISSUE TITLE
Warning in caddy logs

### ISSUE THREAD

**Issue by Gandulf78** [caddyserver/caddy-docker#355]
Hi.
I see the following warning in my caddy's log. I didn't see any effect though.

{"level":"warn","ts":1717439718.9967573,"msg":"failed to set GOMAXPROCS","error":"open /sys/fs/cgroup/cpu/cpu.cfs_quota_us: no such file or directory"}

My docker-compose is as follows:

> version: "3.9"
services: 
  caddy:
    image: gandulf78/caddy-cloudflare-ip:2.8.4
    container_name: caddy
    restart: always
    ports:
      - "3443:443"
      - "3443:443/udp"
    env_file:
      - caddy.env
    volumes:
      - /volume1/Laurent/docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - /volume1/Laurent/docker/caddy/data:/data
      - /volume1/Laurent/docker/caddy/config:/config
      - /volume1/Laurent/docker/caddy/assets:/assets:ro
      - /volume1/Laurent/docker/podsync/data/:/podsync_data:ro
    dns:
      - 1.1.1.3
      - 1.0.0.3
    cap_add:
      - NET_BIND_SERVICE
    healthcheck:
      test: ["CMD", "caddy", "version"]  
    extra_hosts:
    - "host.docker.internal:host-gateway"       
    networks:
      macvlan0:
         ipv4_address: 10.0.0.200
      internal:

My Caddy image is built with the following Dockerfile:

> 
FROM caddy/caddy:2.8.4-builder-alpine AS builder
RUN go install --x github.com/caddyserver/xcaddy/cmd/xcaddy@latest
RUN xcaddy build v2.8.4 \
    --with github.com/caddy-dns/cloudflare \
    --with github.com/caddyserver/transform-encoder
FROM caddy/caddy:2.8.4-alpine
RUN addgroup -S caddygroup && adduser -S caddyuser -G caddygroup
RUN mkdir -p /etc/caddy /data /config && \
    chown -R caddyuser:caddygroup /etc/caddy /data /config
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
USER caddyuser
EXPOSE 80
EXPOSE 443

CMD ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]

Caddy is running on Sinology DS420+.

**Comment by Gandulf78** [comment]
Fixed by adding GOMAXPROCS=2 in the environment variables.

**Comment by mholt** [comment]
Huh. Weird! Thanks for the workaround.

**Comment by francislavoie** [comment]
That's not the official Caddy docker image that you're using, so we can't help with that. You should get help from the maintainer of that image.
