### ISSUE TITLE
Config and data are not persisted even though I am mounting volumes

### ISSUE THREAD

**Issue by neuronflow** [caddyserver/caddy-docker#42]
Unfortunately the config and data folders stay empty when mounting as volumes. I realized this when hitting rate limits after restarting my docker compose a couple of times. Is there anything I can do now to obtain the certs? I tried adding quotes around the volumes which I did not have before. What am I doing wrong?

Dockerfile
```
FROM caddy/caddy:alpine
COPY Caddyfile /etc/caddy/Caddyfile
```

my docker-compose
```
# run this with: "  CURRENT_UID=$(id -u):$(id -g) docker-compose up ""
version: "3"
services:
  percy:
    # docker run -it -p 80:80 -p 443:443 -p 2019:2019 --rm --name perception_caddy perception_caddy
    image: perception_caddy
    container_name: percy
    hostname: percy
    user: root
    # user: ${CURRENT_UID}
    ports:
      - 443:443
      - 80:80
      # - 2020:2020
    volumes:
      # Just a note - as of the latest caddy/caddy images, these locations are now /config/caddy and /data/caddy. See the (new!) docs for some details: https://github.com/caddyserver/caddy-docker#️-a-note-about-persisted-data 1
      - "./caddy_secrets/caddy_lets_encrypt_storage:/data"
      - "./caddy_secrets/caddy_config_storage:/config"
    # sysctls:
    #   - net.ipv4.ip_unprivileged_port_start=0
    # cap_add:
    #   - CAP_NET_BIND_SERVICE
```

**Comment by neuronflow** [comment]
I started searching in the docker for `config` and `data`:
```
/ # find . -type d | grep config
./root/.config
./root/.config/caddy
```
could it be that I should mount to /root/.config ?

a `data` folder was nowhere to be found.

as stated above my docker is based on `caddy/caddy:alpine`

**Comment by hairyhenderson** [comment]
@neuronflow if you're seeing `/root/.config/caddy` in your container, then you're not running the latest container.

Try running `caddy/caddy:v2.0.0-beta.15-alpine`, or just doing a `docker pull caddy/caddy:alpine` or even just a `docker-compose pull` first.

**Comment by neuronflow** [comment]
@hairyhenderson thank you that was it..doh, I feel stupid - sorry, consider this issue resolved!

now I have to wait 7 days to continue or is there anything I can do for the moment?
I can try switching to different subdomains for the moment, but my main domain is also affected :/

```
percy            | 2020/03/03 14:29:02 [ERROR][translatum.xyz] failed to obtain certificate: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many certificates already issued for exact set of domains: translatum.xyz: see https://letsencrypt.org/docs/rate-limits/, url: (attempt 2/2; challenge=http-01)
```

**Comment by hairyhenderson** [comment]
@neuronflow unfortunately yes you'll have to wait until the rate-limit expires. If you want to do more testing you can use the LE staging environment - see https://caddyserver.com/docs/automatic-https#testing for details!

**Comment by hairyhenderson** [comment]
I'll close this issue now since it's resolved 😉
