### ISSUE TITLE
Wrong volume paths?

### ISSUE THREAD

**Issue by mlaily** [caddyserver/caddy-docker#47]
Hello,

Is something wrong with the documentation, or with the image?

The doc says we should use two volumes mounted on `/data` and `/config`, but when I do that, the only thing that gets created inside by the container is an empty `caddy` directory.

After some investigations, it appears the interesting files are instead created in other volumes, mounted on `/data/caddy` and `/config/caddy`.

Executing `docker exec caddy mount` returns the following (output truncated for legibility):
```
/dev/mapper/docker-8:2-1365-c242539dd94a31a5f3a459ac0e60335ce9f5ebca2e8681424865c1e1be300904 on / type xfs 
[...]
/dev/sda2 on /data type ext4 (rw,relatime,errors=remount-ro)
/dev/sda2 on /config type ext4 (rw,relatime,errors=remount-ro)
/dev/sda2 on /etc/caddy type ext4 (rw,relatime,errors=remount-ro)
/dev/sda2 on /config/caddy type ext4 (rw,relatime,errors=remount-ro)
/dev/sda2 on /data/caddy type ext4 (rw,relatime,errors=remount-ro)
/dev/sda2 on /etc/resolv.conf type ext4 (rw,relatime,errors=remount-ro)
/dev/sda2 on /etc/hostname type ext4 (rw,relatime,errors=remount-ro)
/dev/sda2 on /etc/hosts type ext4 (rw,relatime,errors=remount-ro)
[...]
```

That seems to confirm this.

I tried mounting `/data/caddy` and `/config/caddy` instead of `/data` and `/config/caddy` and it seems to be working...

If it's important, I'm trying to write a docker-compose.yml file, to start caddy.

(I'm still new to docker, so I'm not entirely sure I'm doing everything properly)

**Comment by hairyhenderson** [comment]
@mlaily my apologies - you're right - I'll adjust things to fix this 🙂

**Comment by mlaily** [comment]
Thanks! :)

**Comment by hairyhenderson** [comment]
You're welcome! 🙇
