### ISSUE TITLE
Document tags

### ISSUE THREAD

**Issue by thenewguy** [caddyserver/caddy-docker#57]
It would be helpful if the README at https://hub.docker.com/r/caddy/caddy listed the tags one should use.  I.e. :2, :2.0, :2.0.20, etc

**Comment by francislavoie** [comment]
For now, you can find that info here: https://github.com/caddyserver/caddy-docker#supported-tags-and-respective-dockerfile-links

**Comment by thenewguy** [comment]
Sounds good.

**Comment by hairyhenderson** [comment]
BTW the tags will be documented in the official image's documentation, once that's merged.

See https://github.com/docker-library/official-images/pull/7574 and https://github.com/docker-library/docs/pull/1667 for reference.

**Comment by olivierdalang** [comment]
The tags on the readme are out of date at time of writing (`v2.0.0-beta.15` instead of `2.0.0-rc.1`). Better to remove if it's not updated automatically...

**Comment by hairyhenderson** [comment]
@olivierdalang sorry, I'm working on the automation right now!
