### ISSUE TITLE
add an option to enable QUIC

### ISSUE THREAD

**Issue by marten-seemann** [caddyserver/caddy-docker#68]
It would be nice if there was an option (maybe an ENV variable) to enable QUIC.
Note that in this case, we'll also need to `EXPOSE 443/udp`.

**Comment by francislavoie** [comment]
Would this be as a separate option from `experimental_http3` ?

**Comment by marten-seemann** [comment]
I wasn't aware that this a config option now. I just tried to use it, but it doesn't work:
```
example.com {
  root * /var/www
  file_server browse
  experimental_http3
}
```
Caddy says `adapting config using caddyfile: /etc/caddy/Caddyfile:4: unrecognized directive: experimental_http3`.

**Comment by francislavoie** [comment]
It's a global option: https://caddyserver.com/docs/caddyfile/options

```
{
  experimental_http3
}

example.com {
  root * /var/www
  file_server browse
}
```

**Comment by marten-seemann** [comment]
Thank you! It works.

> Note that in this case, we'll also need to EXPOSE 443/udp.

Do we need to do this?

**Comment by francislavoie** [comment]
That's also something you can just do when you run Docker with `-p 443:443/udp`.

**Comment by marten-seemann** [comment]
Yes, I was just wondering if it should be added to https://github.com/caddyserver/caddy-docker/blob/44e9455c4e3c5c0cfb65517c95a84fe87bdd7a22/alpine/Dockerfile#L45-L47
So that it works out of the box when users set the `experimental_http3` option.

**Comment by francislavoie** [comment]
`EXPOSE` doesn't actually publish the port, it wouldn't change anything to add that. It's more just "documentation" for what's available. If you want to make it accessible from outside the docker network, you still need to use `-p`. See https://docs.docker.com/engine/reference/builder/#expose

We could still add it though, but I'm thinking it's not really necessary until HTTP/3 is no longer experimental.

**Comment by hairyhenderson** [comment]
Once HTTP/3 is out of experimental, would it make sense to add `experimental_http3` to the default `Caddyfile`?

If so that'd be something that should be added to https://github.com/caddyserver/dist/tree/master/config/Caddyfile

**Comment by mholt** [comment]
Once HTTP/3 is no longer experimental, there's a chance it will be enabled by default without needing any directive -- but I'm not sure yet, it depends on some things. (And note that experimental is different from the spec being finalized.) It definitely shouldn't be on by default while still experimental though.

**Comment by hairyhenderson** [comment]
Ok. Based on that, does it make sense to close this issue?

**Comment by francislavoie** [comment]
I would say so. We can revisit when HTTP/3 is no longer experimental.

**Comment by nicheosala** [comment]
Has anyone managed to get HTTP3 working?
I know this is an experimental feature: for this reason, I would like to be able to *experience* it.
I've added the global option `{experimental_http3}` to my Caddyfile and I know my Firefox browser support it (just visit https://quic.nginx.org and after a bit of configuration you'll se the protocol used is HTTP3). However, I cannot get it work with Caddy.
