### ISSUE TITLE
Debian-based image?

### ISSUE THREAD

**Issue by frenchvandal** [caddyserver/caddy-docker#80]
Is it planned and/or worth considering that Caddy offers an official Debian-based image?

Thanks!

**Comment by francislavoie** [comment]
There aren't really any advantages to that over alpine.

Why would you need that specifically?

**Comment by frenchvandal** [comment]
To optimize the Docker cache during build, because all the web apps I serve with Caddy are based on Debian Buster. So that would be a suitable option.

(I tried to go full Alpine but one of my main web apps fails because of a weird TZ issue)

**Comment by francislavoie** [comment]
Considering the Alpine image is only 14MB compressed, I really don't think that's a problem here.

**Comment by hairyhenderson** [comment]
@frenchvandal what is the TZ issue? Is it related to #58 maybe?

**Comment by frenchvandal** [comment]
@hairyhenderson thanks for the reference. Nothing to do with Caddy actually (I guess). In my conf, Caddy does a reverse proxy to an Apache container. With the Alpine image, Apache returns a 500 error because of an invalid timezone. Using the very same Apache conf, I have no issues with the Debian image. I do not understand because I do not care about TZ.
I will start again from scratch after some rest, maybe I messed up with something in my Dockerfile.

And no worries, as Francis put it, the size is not that important 😄 Thanks for hearing me out!

**Comment by hairyhenderson** [comment]
@frenchvandal not sure I understand totally 😂... If you have trouble building an image from `caddy` or `caddy:builder` though, feel free to log a new issue here 🙂

**Comment by cemremengu** [comment]
Is it possible to reopen this? Currently one of our customers are blocking alpine images for various reasons and we are having trouble deploying caddy. Just a single variant of Debian should be enough. Would be happy to contribute if you are ok with it

**Comment by francislavoie** [comment]
I don't see why that should be something we support. "One of our customers is blocking it" isn't a compelling argument.

You can make your own images trivially if you can't use alpine, just download the Caddy binary from GitHub (as this image does) or build from source with xcaddy in your own Dockerfile.

**Comment by cemremengu** [comment]
Thanks for your work and taking your time to reply!

I would like to provide a more compelling argument but at this point it is just a preference so there is none unfortunately.

I always consider Alpine as an optional distro for power users and find it a bit "strange" having it as the only supported Linux distro especially when the size different compared to Debian Slim is 50MB. If you need to support only one distro, I believe it should be Debian.

Just my 2 cents
