### ISSUE TITLE
Custom caddy image, webserver not starting

### ISSUE THREAD

**Issue by Maxiride** [caddyserver/caddy-docker#88]
For the sake of playing with the tools and learn how to bundle an application composed of its frontend and backend all bundled together I am building a SPA which I would like to serve with Caddy in an easy to deploy image.

As of now I am only trying to deploy the frontend.

Here is the Dockerfile which builds the image:
```dockerfile
# Nuxt frontend
FROM node:11.13.0-alpine as nuxt-builder

WORKDIR /app/frontend
COPY /frontend .

RUN npm install && npm run build

# Build result is placed in /dist

# Caddy webserver
FROM caddy:2.0.0

COPY --from=nuxt-builder /app/frontend/dist /usr/share/caddy/
COPY Caddyfile /etc/caddy/Caddyfile

EXPOSE 80
```

Caddyfile
```
root /usr/share/caddy/
tls off
```

/usr/share/caddy does contain the generated index.html and additional files.
However when running the image there is no response:

```
C:\Users\maxir> docker run -p 8080:80 -d test-caddy

C:\Users\maxir>curl localhost:8080
curl: (52) Empty reply from server
```

Am I doing it wrong?

**Comment by francislavoie** [comment]
Yes, unfortunately your Caddyfile is incorrect. You need to have a site label as the first thing in your file. See the structure here: https://caddyserver.com/docs/caddyfile/concepts#structure

For next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for tracking improvements to our Docker deployments. Don't forget to fill out the thread template so we can help you!

**Comment by Maxiride** [comment]
Thank you for redirectin me =)
