### ISSUE TITLE
Where does Caddy keep their certificates?

### ISSUE THREAD

**Issue by lemchen** [caddyserver/caddy-docker#89]
Where does Caddy store all the cert info, where I can copy and paste it outside the container?

**Comment by lemchen** [comment]
it seems to be  /data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/
so  i can do this -v /my-certificates/:/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

For next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
