### ISSUE TITLE
Examples building

### ISSUE THREAD

**Issue by Stonedestroyer** [caddyserver/caddy-docker#90]
I propose an example of how to build additional modules into the Docker container, similar to v1 had plugin args.

**Comment by Stonedestroyer** [comment]
Nobody saw this.

**Comment by hairyhenderson** [comment]
@Stonedestroyer _I_ saw this :trollface:

(and just in case anyone comes along and wonders where the examples are, see https://hub.docker.com/_/caddy and search in the page for `Building your own Caddy-based image`)

**Comment by Stonedestroyer** [comment]
I read that like 3 times before I understood it was for the docker images and not standalone docker binaries my bad.
